spring.application.name=Leave-Management-System-Backend

# JWT settings
jwt.secret=ReplaceThisVeryLongSecretKeyChangeInProd123456
jwt.access_expiration_seconds=900
jwt.refresh_expiration_seconds=604800

# Mail settings
spring.mail.host=localhost
spring.mail.port=2500
spring.mail.username=no-reply@company.com
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false


spring.datasource.url=jdbc:postgresql://ep-solitary-poetry-aor1f5eq-pooler.c-2.ap-southeast-1.aws.neon.tech/lms_db?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=${NEON_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
